"""SFT warmup for multi-turn KG agent trajectories.

Trains the model on gold multi-turn trajectories generated by
generate_sft_trajectories.py, teaching it the tool-use format:
  <think>reasoning</think>
  <search>get_tail_relations(entity)</search>
  ...
  <answer>final answer</answer>

Uses TRL's SFTTrainer with LoRA (DoRA + rsLoRA).

Usage:
    python src_verl/training/sft_multiturn.py \
        --config configs_verl/sft_multiturn.yaml
"""

from __future__ import annotations

import argparse
import json
import logging
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

import torch
import yaml
from datasets import Dataset
from peft import LoraConfig, get_peft_model
from transformers import AutoModelForCausalLM, AutoTokenizer
from trl import SFTConfig, SFTTrainer

logger = logging.getLogger(__name__)


@dataclass
class SFTMultiturnConfig:
    """Configuration for multi-turn SFT warmup."""

    # Model
    model_name: str = "Qwen/Qwen2.5-1.5B-Instruct"
    torch_dtype: str = "bfloat16"
    attn_implementation: str = "flash_attention_2"

    # LoRA
    lora_r: int = 16
    lora_alpha: int = 32
    lora_target_modules: str = "all-linear"
    lora_dropout: float = 0.05
    use_dora: bool = True
    use_rslora: bool = True

    # Training
    num_train_epochs: int = 2
    per_device_train_batch_size: int = 4
    gradient_accumulation_steps: int = 4
    learning_rate: float = 2e-4
    gradient_checkpointing: bool = True
    max_seq_length: int = 2048
    logging_steps: int = 10
    save_strategy: str = "epoch"
    warmup_ratio: float = 0.05
    optim: str = "adamw_8bit"

    # Data
    train_file: str = "data/processed/sft_trajectories.jsonl"
    output_dir: str = "outputs/verl-sft"

    # Wandb
    wandb_project: str = "kg-align-verl"
    wandb_run_name: str = "sft-multiturn"

    @classmethod
    def from_yaml(cls, path: Path) -> SFTMultiturnConfig:
        with open(path, "r") as f:
            data = yaml.safe_load(f)

        config = cls()
        for section in data.values():
            if isinstance(section, dict):
                for key, value in section.items():
                    if hasattr(config, key):
                        setattr(config, key, value)
        return config


def load_trajectories(path: Path) -> list[dict[str, Any]]:
    """Load multi-turn trajectories from JSONL."""
    records: list[dict[str, Any]] = []
    with open(path, "r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if line:
                records.append(json.loads(line))
    logger.info("Loaded %d trajectories from %s", len(records), path)
    return records


def trajectories_to_dataset(
    records: list[dict[str, Any]],
    tokenizer: Any,
) -> Dataset:
    """Convert trajectories to HF Dataset for SFTTrainer.

    Applies the tokenizer's chat template to produce a pre-formatted 'text'
    column, since the installed TRL version does not auto-detect 'messages'.
    """
    all_texts: list[str] = []

    for record in records:
        trajectory = record["trajectory"]

        # Keep native 'tool' role — Qwen2.5's chat template supports it
        # (renders as <|im_start|>user\n<tool_response>\n...\n</tool_response>).
        # This MUST match the format used during GRPO rollouts (verl's
        # ToolAgentLoop also uses role="tool") and evaluation.
        messages: list[dict[str, str]] = [
            {"role": msg["role"], "content": msg["content"]}
            for msg in trajectory
        ]

        text = tokenizer.apply_chat_template(
            messages, tokenize=False, add_generation_prompt=False
        )
        all_texts.append(text)

    dataset = Dataset.from_dict({"text": all_texts})
    logger.info("Created dataset with %d samples", len(dataset))
    return dataset


def main() -> None:
    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s - %(name)s - %(levelname)s - %(message)s",
    )

    parser = argparse.ArgumentParser(description="SFT warmup for multi-turn KG agent.")
    parser.add_argument(
        "--config",
        type=Path,
        default=Path("configs_verl/sft_multiturn.yaml"),
        help="YAML config path.",
    )
    args = parser.parse_args()

    # Load config
    if args.config.exists():
        config = SFTMultiturnConfig.from_yaml(args.config)
    else:
        logger.warning("Config not found at %s, using defaults", args.config)
        config = SFTMultiturnConfig()

    logger.info("SFT Config: %s", config)

    # Load tokenizer
    tokenizer = AutoTokenizer.from_pretrained(config.model_name)
    if tokenizer.pad_token is None:
        tokenizer.pad_token = tokenizer.eos_token
    tokenizer.padding_side = "right"  # SFT uses right padding

    # Load model
    dtype_map = {"bfloat16": torch.bfloat16, "float16": torch.float16}
    model_kwargs: dict[str, Any] = {
        "torch_dtype": dtype_map.get(config.torch_dtype, torch.bfloat16),
    }

    # Try flash attention, fall back to SDPA
    try:
        model_kwargs["attn_implementation"] = config.attn_implementation
        model = AutoModelForCausalLM.from_pretrained(config.model_name, **model_kwargs)
    except Exception:
        logger.warning("Flash attention not available, falling back to SDPA")
        model_kwargs["attn_implementation"] = "sdpa"
        model = AutoModelForCausalLM.from_pretrained(config.model_name, **model_kwargs)

    # LoRA config
    peft_config = LoraConfig(
        r=config.lora_r,
        lora_alpha=config.lora_alpha,
        target_modules=config.lora_target_modules,
        lora_dropout=config.lora_dropout,
        use_dora=config.use_dora,
        use_rslora=config.use_rslora,
        bias="none",
        task_type="CAUSAL_LM",
    )

    # Load data
    train_path = Path(config.train_file)
    if not train_path.exists():
        logger.error("Training file not found: %s", train_path)
        return

    records = load_trajectories(train_path)
    train_dataset = trajectories_to_dataset(records, tokenizer)

    # SFT training config
    sft_config = SFTConfig(
        output_dir=config.output_dir,
        num_train_epochs=config.num_train_epochs,
        per_device_train_batch_size=config.per_device_train_batch_size,
        gradient_accumulation_steps=config.gradient_accumulation_steps,
        learning_rate=config.learning_rate,
        gradient_checkpointing=config.gradient_checkpointing,
        max_seq_length=config.max_seq_length,
        logging_steps=config.logging_steps,
        save_strategy=config.save_strategy,
        warmup_ratio=config.warmup_ratio,
        optim=config.optim,
        bf16=True,
        report_to="wandb",
        run_name=config.wandb_run_name,
        dataset_text_field="text",
        seed=42,
    )

    # Create trainer — SFTTrainer auto-creates DataCollatorForLanguageModeling
    trainer = SFTTrainer(
        model=model,
        args=sft_config,
        train_dataset=train_dataset,
        tokenizer=tokenizer,
        peft_config=peft_config,
    )

    # Train
    logger.info("Starting SFT training...")
    trainer.train()

    # Save
    trainer.save_model(config.output_dir)
    tokenizer.save_pretrained(config.output_dir)
    logger.info("Model saved to %s", config.output_dir)


if __name__ == "__main__":
    main()
